
console.log("test driver and all drive below")

const test = new hashMap()

test.set('apple', 'red')
test.set('banana', 'yellow')
test.set('carrot', 'orange')
test.set('dog', 'brown')
test.set('elephant', 'gray')
test.set('frog', 'green')
test.set('grape', 'purple')
test.set('hat', 'black')
test.set('ice cream', 'white')
test.set('jacket', 'blue')
test.set('kite', 'pink')
test.set('lion', 'golden')

console.log(test.length())
//console.log(test.loadFactor())
//console.log(test.entries())
//console.log(test.set('moon', 'silver'))
//console.log(test.get('hat'))
//console.log(test.has('kite'))
//console.log(test.remove('apple'))
//console.log(test.length())
//console.log(test.clear())
//console.log(test.keys())
//console.log(test.values())
//console.log(test.entries())
